### ISSUE TITLE
Error while logging in:

### ISSUE THREAD

**Issue by RobinReinecke** [mm28ajos/docker-dynamic-dns-netcup-api#1]
Hi,
first of all: thanks for your work. I'm trying to migrate my (currently) local running script to your docker image but get the following error:

```
Warning: Trying to access array offset on value of type null in /usr/src/dynamic-dns-netcup-api/functions.php on line 319

Warning: Trying to access array offset on value of type null in /usr/src/dynamic-dns-netcup-api/functions.php on line 323
[2021/03/07 08:52:01 +0000][ERROR] Error while logging in:  Exiting.
```

It seems like the login does not work. I double checked my credentials.  My docker-compose is completely standard. But I disabled IPv6 and the mail stuff.
Thanks for help

**Comment by mm28ajos** [comment]
Could you try to omit the quotes around the API argument? 

My hard drive just crashed :sleepy:. Will take some days to have a look at the issue.

**Comment by RobinReinecke** [comment]
Wow it seems like it worked 😍! Thanks!

**Comment by mm28ajos** [comment]
I removed the APIURL setting completely and updated the readme file.
