### ISSUE TITLE
Feature: Env-Variable to toggle quiet option

### ISSUE THREAD

**Issue by RobinReinecke** [mm28ajos/docker-dynamic-dns-netcup-api#2]
Hi 😎
I have an idea for a useful enhancement: It would be nice to have an environment option to toggle the --quiet parameter. This would help to debug and find errors in faulty configurations.
https://github.com/mm28ajos/docker-dynamic-dns-netcup-api/blob/2733c1214e4cd6118214f566b49ad112284137b0/Dockerfile#L16

**Comment by mm28ajos** [comment]
Addressed by this commit https://github.com/mm28ajos/docker-dynamic-dns-netcup-api/commit/17ecc0fae7d20a822abca65c5e3af584e551a5e9
