### ISSUE TITLE
Error while updating DNS Zone:  Exiting

### ISSUE THREAD

**Issue by fharten** [mm28ajos/docker-dynamic-dns-netcup-api#3]
Hi,
first of all: thanks for the great work. I'm currently trying to setup the docker image to run in portainer on my unraid server. I put the customernr, etc. in env variables. This is my log:

`PHP Notice:  Undefined variable: apirurl in /usr/src/dynamic-dns-netcup-api/functions.php on line 450
PHP Notice:  Trying to access array offset on value of type null in /usr/src/dynamic-dns-netcup-api/functions.php on line 452
PHP Notice:  Trying to access array offset on value of type null in /usr/src/dynamic-dns-netcup-api/functions.php on line 456
[2022/02/25 09:41:35 +0000][ERROR] Error while updating DNS Zone:  Exiting.
[2022/02/25 09:41:35 +0000][ERROR] Failed to set TTL... Continuing.`

Thanks in advance!

**Comment by fharten** [comment]
nevermind. it still works. thanks a lot for the great work! :)

**Comment by mm28ajos** [comment]
So it works for you? Just reopen the issue otherwise :)
